os: Visual Studio 2015
version: '{branch}.0.{build}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: zD+GQJ7l3fpqQgvKM7qOOXBprbzVwxVtWLam6ZsK6ILUzrLWiom/CyU8+ppZAodB
build_script:
  - build.cmd
test_script:
  - test.cmd
clone_depth: 1
test: on
deploy: off
artifacts:
  - path: src/NetCore.Simple.ObjectIdentifier/bin/Release/*.nupkg
    name: NetCore.Simple.ObjectIdentifier
